mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hj.tj.gohome.entity

auth:
  jwt:
    secret: ed92792d87d629d84cf589c5acfe257f
    expire: 2592000

#默认使用配置
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1MB
      enabled: true
  datasource:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 1
  jackson:
    serialization:
      write-dates-as-timestamps: true

---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/y_website?useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 821075358q
server:
  port: 8080
